**What is numpy?**


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

**Numpy Arrays Vs Python Sequences**


*  NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

*   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

*   NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

*  A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

**Creating Numpy Arrays**

In [ ]:
#np.array

import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D

b  = np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#dtype

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
#np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
#np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random

np.random.random((3, 4))

array([[3.07354315e-01, 4.12676829e-01, 5.45554385e-01, 6.10249397e-01],
       [9.29017798e-01, 4.37405933e-01, 7.34546066e-01, 3.64052179e-02],
       [4.74413500e-01, 3.15188143e-04, 8.44591099e-01, 6.70212219e-01]])

In [ ]:
#np. linspace

np.linspace(-10,12,10,dtype=int)

array([-10,  -8,  -6,  -3,  -1,   2,   4,   7,   9,  12])

In [ ]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [ ]:
import numpy as np
a1 =  np.arange(10,dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim

a3.ndim

3

In [ ]:
#shape

print(a3.shape)

(2, 2, 2)


In [ ]:
#size

print(a2.size)

12


In [ ]:
#itemsize

print(a3.itemsize)

8


In [ ]:
#d.type

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype


In [ ]:
#astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operation

#arithmetic

a1**2
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#relational

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#vector operation

a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[18., 58., 47.],
       [42., 79.,  5.],
       [66., 70., 33.]])

In [ ]:
#max/min/sum/product

np.prod(a1,axis =0)

array([ 49896., 320740.,   7755.])

In [ ]:
#mean/median/std/var

np.var(a1, axis = 1)

array([284.66666667, 912.66666667, 274.88888889])

In [ ]:
#trignometric function

np.sin(a1)

array([[-0.75098725,  0.99287265,  0.12357312],
       [-0.91652155, -0.44411267, -0.95892427],
       [-0.02655115,  0.77389068,  0.99991186]])

In [ ]:
#dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents

np.exp(a1)

array([[6.56599691e+07, 1.54553894e+25, 2.58131289e+20],
       [1.73927494e+18, 2.03828107e+34, 1.48413159e+02],
       [4.60718663e+28, 2.51543867e+30, 2.14643580e+14]])

In [4]:
#round/floor/ceil
import numpy as np
np.ceil(np.random.random((2,3)) * 100)

array([[95., 19., 27.],
       [25., 85., 68.]])

#Indexing and Slicing

In [5]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [6]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a2[1,0]

np.int64(4)

In [13]:
a3[1,0,1]

np.int64(5)

In [14]:
a3[1,1,0]

np.int64(6)

In [15]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a1[2:5:2]

array([2, 4])

In [17]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [19]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [20]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a2[1,0::3]

array([4, 7])

In [23]:
a2[0,:]

array([0, 1, 2, 3])

In [24]:
a2[:,2]

array([ 2,  6, 10])

In [27]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [29]:
a3 = np.arange(27).reshape(3,3,3)

In [30]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [32]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [33]:
a3[0,1:2,:]

array([[3, 4, 5]])

#Iterating

In [35]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [36]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [37]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [41]:
#Transpose

np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [42]:
#ravel

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

In [44]:
#horizontal Stacking - Should have same rows

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [46]:
#Vertical Stacking - Should have same columns

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [47]:
#Horizontal Splitting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [52]:
#Vertical Split

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]